SurveyMarkSetMessage: "&6Setting your survey marker.&r"
SurveyMarkReplaceMessage: "&6Updating your survey marker.&r"
SurveyMarkCleared: "&6Clearing your survey marker.&r"
SurveyMarkDestroyed: "&6Your survey marker was destroyed.&r"
SurveyMarkNotSet: "&6You have no active survey marker.&r"

SurveyReportHeader: "&6&nBlock Survey Report&r"
North: "&cNorth"
South: "&cSouth"
East: "&cEast"
West: "&cWest"
Up: "&cUp"
Down: "&cDown"
DueNorth: "&c&odue North"
DueSouth: "&c&odue South"
DueEast: "&c&odue East"
DueWest: "&c&odue West"
DueUp: "&c&odirectly Above"
DueDown: "&c&odirectly Below"
ReportLine: "&b%d&e blocks %s&r"